// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]?.replace(
      /([?&])sslmode=(?:prefer|require|verify-ca)(?=&|$|")/i,
      "$1sslmode=verify-full"
    ),
  },
});